### PR TITLE
[FEATURE] Add Coding Guidelines for other file formats

### PR DESCRIPTION
**Pull request by sypets**
- Move sections on other file formats from introduction to seperate chapters
- Add more information for other file formats
- Add section on TypoScript
- Move current CGL chapters about PHP down one level

Related: #218

### CODE REVIEW

**Comment by sypets** [comment]
# todos

* [ ]  check if redirects can be added for the changed URLs of existing pages so as not to introduce new broken links (@sypets will check this)

**Comment by DanielSiepmann** [comment]
They can be added, we have an Apache and `.htaccess`. But we should talk to martin regarding how to manage this. Currently there is a symlinked file for easier reuse.

**Comment by marble** [comment]
Hi @lolli42, we are at the T3DocTeam sprint right now and are trying to find out what to do with open pull requests. Current identified goal at the moment: At least give each PR an ASSIGNEE. This is an example of a PR where only someone of the core team can do the next step (merge, modify, drop).

The general idea we've just come up with is that each PR should have an assignee soon. That is the person that cares about the PR, it doesn't necessarily have to be the one who solves that PR.

Thinking about the general concept: When we find out only the core team can continue - whom should we assign in a first step?

**Comment by lolli42** [comment]
Sorry for the delay. I rebased locally and will merge that now. Great change Sybille, thank you so much!

**Comment by sypets** [comment]
Thank you!

**Pull request merged**
