### PR TITLE
Add list of commands

### PR DESCRIPTION
**Pull request by sypets**
Related: #2750
Related: #3094

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
We want to create a list of commands with all options and arguments automatically. Personally; I schedule this for autumn.
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/2750

This PR can be an intermediate solution. However, I propose to use one page per command.

**Comment by sypets** [comment]
> We want to create a list of commands with all options and arguments automatically

I hope in that case it will be possible to add additional information.

> However, I propose to use one page per command.

I assume the automatically generated list will be one page per command. I suggest to use a naming which can be reproduced automatically, e.g. 

`:abc:def: > AbcDef`

Please comment if different naming scheme should be used.

Will push further changes ...

**Comment by brotkrueml** [comment]
> > We want to create a list of commands with all options and arguments automatically
> 
> I hope in that case it will be possible to add additional information.

That is the idea ;-)

> I assume the automatically generated list will be one page per command. I suggest to use a naming which can be reproduced automatically, e.g.
> 
> `:abc:def: > AbcDef`

Hmm, don't know yet. Maybe an include of the generated files like for the code snippets, so we are flexible and can add more information (like "deprecation" or "version added" manually or special examples - if needed). In this case the naming of the files does not matter. But go ahead and use your suggestion.

**Comment by sypets** [comment]
Maybe it is better to wait until the automatic generation is available. I don't want my work to go to waste, but we could keep this open.

I don't mind doing the work to restructrure (it is half finished) but now I am wondering if individual pages are really such a good idea. The text is often very short. Also, I don't think you really need a full list of all options and it just clutters up the space. So there are some questions open and maybe this will be handled differently once the automatic generation is available. I don't want to spend time on several iterations of this PR if unnecessary.

So I suggest to keep this PR as is as draft so the text can be reused when required. (Alternatively we could also store it somewhere else.

Also, I started to create a list of the scheduler tasks. This is shorter and would be in the core scheduler documentation (in the core). Not sure if this should be generated automatically as well (I assume not).

**Comment by brotkrueml** [comment]
We should not describe the various commands and their options in the docs. They are documented well via the CLI interface which is enough. Additionally, the list of commands depend or your installed system extensions and 3rd-party extensions.

**Pull request closed without merging**
