### PR TITLE
Fix AbstractXmlSitemapDataProvider path

### PR DESCRIPTION
**Pull request by fritzdacat**

### CODE REVIEW

**Review by DavidBruchmann — COMMENTED** [review]
Why?

**Comment by fritzdacat** [comment]
Because in the frontend it looked like "TYPO3CMSSeoXmlSitemapAbstractXmlSitemapDataProvider "

**Comment by brotkrueml** [comment]
I merged a PR from him for 10.4 yesterday: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/1e6eecc362902ffb4bd1378c7636c0f714711d19 . In 11.5 and main it was already correct.

But 9.5 is EOL as community edition and AFAIK no 9.5 docs are rendered anymore.

**Comment by linawolf** [comment]
Was solved by https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/1e6eecc362902ffb4bd1378c7636c0f714711d19

**Pull request closed without merging**
