### PR TITLE
[BUGFIX] Fix wrong regular expression in routeEnhancers

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
Should we also Backport this to 10.4 and 9.5?

**Comment by simonschaufi** [comment]
@linawolf sure, it's a bug ;)

**Comment by linawolf** [comment]
@simonschaufi ok, I take care of it. 

Next time just write Releases: master, 10.4, 9.5 in the commit message of the PR:

https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/CommitMessages.html

**Comment by simonschaufi** [comment]
@linawolf  ok. I'm not used about the workflow yet.

PS: do you have an idea why there is no syntax highlighting in this section? https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Routing/AdvancedRoutingConfiguration.html#extbase-plugin-enhancer

**Comment by linawolf** [comment]
@simonschaufi 

there is probably an syntax error in the YAML. If you can fix it please make a PR if not an issue...

You can also ask your questions on slack in the #typo3-documentation channel. In the comments on a closed PR they might get lost

**Pull request merged**
