### PR TITLE
use full name: modal dialog window

### PR DESCRIPTION
**Pull request by franzholz**
What is a "modal"?

### CODE REVIEW

**Comment by mbrodala** [comment]
The term is coined by Bootstrap whose library is used here: https://getbootstrap.com/docs/5.1/components/modal/

But indeed there are some variants to this: https://en.wikipedia.org/wiki/Modal_window

Not sure we need the term _dialog_ here since a _modal_ / _modal window_ implies that it requires interaction, just like a dialog.

**Comment by franzholz** [comment]
I have checked the term "modal". Online dictionaries do not know it.

https://www.dict.cc/?s=modal
https://de.langenscheidt.com/englisch-deutsch/modal
https://www.linguee.com/english-german/search?source=auto&query=modal

**Comment by mbrodala** [comment]
It's a short name for _modal window_ and rather common in the JS world. So looking at the target audience we can assume that just _modal_ is understood. But nobody will complain if it is named _modal window_ instead. ;-)

**Comment by franzholz** [comment]
Hm, do you mean that the target readers of TYPO3 documentation are only computer science experts?

**Comment by mbrodala** [comment]
No, never wrote that. The target audience of the Core API reference are developers.

**Review by linawolf — APPROVED** [review]

**Comment by mbrodala** [comment]
@linawolf Discussion was still ongoing here but oh well. :shrug:

**Pull request merged**
