### PR TITLE
Add advise how to activate acceptance tests in ProjectTesting.rst

### PR DESCRIPTION
**Pull request by DavidBruchmann**

### CODE REVIEW

**Comment by DavidBruchmann** [comment]
Ich hab's übrigens getestet.

**Review by brotkrueml — COMMENTED** [review]
Why only 11.5 and not also main?

Should the file name in line 77 not also be adjusted? There the yaml file is references but it does not exist when cloning the repo.

**Comment by linawolf** [comment]
@DavidBruchmann any news on this PR?

**Comment by DavidBruchmann** [comment]
@brotkrueml here is the file: https://github.com/TYPO3-Documentation/site-introduction/blob/main/.ddev/docker-compose.chrome.yaml.inactive. So I don't know where you see a problem about the filename.
The procedure about the renaming can also be seen in the gihub actions: 

- https://github.com/TYPO3-Documentation/site-introduction/blob/main/.github/workflows/tests.yml#LL16C1-L17C99
- https://github.com/TYPO3-Documentation/site-introduction/blob/main/.github/workflows/tests.yml#LL40C1-L41C99

**Comment by DavidBruchmann** [comment]
@linawolf if it's working with the label `backport 12.4`, that's fine, else it's no problem to create it new for 12.4 and backport from there.
Should the label `backport 10.4` also be applied?

**Comment by DavidBruchmann** [comment]
I made a new PR on main, so it's easier everything.
Closing here,

**Pull request closed without merging**
