### PR TITLE
[CI] Lint code with PHP 8.4

### PR DESCRIPTION
**Pull request by brotkrueml**
Releases: main, 12.4

### CODE REVIEW

**Comment by linawolf** [comment]
PHP 8.4 is not released yet: https://php.watch/versions/8.4 Why not wait for the official release?

**Comment by brotkrueml** [comment]
> PHP 8.4 is not released yet: https://php.watch/versions/8.4 Why not wait for the official release?

Currently the last beta is out and the RC release cycle should start this week. We should provide compatibility with PHP 8.4 early, to ensure our examples are still valid.

TYPO3 itself tests against PHP 8.4 since summer (starting with the alpha releases).

So, now it is time to adjust the pipelines to see if something will cause problems with the new release.

**Comment by linawolf** [comment]
I put the question of when to adopt new PHP feature versions in the docs on the agenda for the next Team meeting. For the time beeing as the changes seem to be backward compatibel and this is only linting I see no harm in adopting them.

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
@brotkrueml automatic backport failed, please make a manual backport if desired

**Pull request merged**
