### PR TITLE
redesign Log Level

### PR DESCRIPTION
**Pull request by franzholz**

### CODE REVIEW

**Comment by franzholz** [comment]
I cannot find where to set this pull request also for the master branch.

**Comment by mbrodala** [comment]
@franzholz The usual approach is to post a change against `master` first and then request backports to other versions.

**Comment by linawolf** [comment]
I think, this would be a good use-case for a definition list: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/DefinitionLists.html 

What do you think?

**Review by franzholz — COMMENTED** [review]
Change chapter log level into a definition list.

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
Needs backport to master @franzholz should this also be backported to 9.5?

**Comment by franzholz** [comment]
I think that a backport to 9.5 is not so important at this moment.

**Pull request merged**
