### PR TITLE
[TASK] Add trailing commas to arguments, match and parameters

### PR DESCRIPTION
**Pull request by brotkrueml**
Trailing commas are already added to arrays - now they are also necessary for other multiline parts. This makes copy/pasting easier and diffs smaller.

Releases: main, 12.4

### CODE REVIEW

**Review by garvinhicking — APPROVED** [review]
Do we have other Repositories where we would need to do the same, for uniformity?

I only quickly scrolled through it all. "Augen zu und let's fix it in post", I'd say. ;)

**Comment by brotkrueml** [comment]
> Do we have other Repositories where we would need to do the same, for uniformity?

Yup, we have. I'll provide PRs for those after this one is merged.

> I only quickly scrolled through it all. "Augen zu und let's fix it in post", I'd say. ;)

The changes are done automatically by php-cs-fixer and the tests are green, so I assume, the changes are fine ;-)

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
@brotkrueml once you are back, this needs to be backported manually

**Comment by garvinhicking** [comment]
(Might be easier to just execute php-cs-fixer again in 12.4 and do a fresh commit without cherries on top?)

**Pull request merged**
