### PR TITLE
Writer configuration

### PR DESCRIPTION
**Pull request by averlon**
I have added a comment inside "Writer configuration" since there is some reference to some examples from my point of view not existent.

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
The "first example" references to the first example above:

    $GLOBALS['TYPO3_CONF_VARS']['LOG']['writerConfiguration']

matches `\Documentation\Examples\Controller`

**Comment by DavidBruchmann** [comment]
actually this is an interesting case where I get the idea that paragraphs or code-blocks could get uuids.
Even the describing text might render wrong after some change, according links would still work.

**Comment by brotkrueml** [comment]
> actually this is an interesting case where I get the idea that paragraphs or code-blocks could get uuids. Even the describing text might render wrong after some change, according links would still work.

The whole logging chapter should be overhauled. When I have more time, will do it. But we can work with anchors and link "first example" to it in the meantime.

**Comment by averlon** [comment]
> The "first example" references to the first example above:
> 
> ```
> $GLOBALS['TYPO3_CONF_VARS']['LOG']['writerConfiguration']
> ```

May be! But this is then not an example for the namespace. If I understand this correct, this example defines the logging for the whole T3 installation.

**Review by linawolf — APPROVED** [review]
I would suggest that you open an issue instead of making a Pull request. The chapter really does need an overhaul.

**Review by linawolf — CHANGES_REQUESTED** [review]
I would suggest that you open an issue instead of making a Pull request. The chapter really does need an overhaul. Clicked the wrong button :(

**Pull request closed without merging**
