### PR TITLE
[DEPRECATION] #94313 - AbstractService class

### PR DESCRIPTION
**Pull request by linawolf**
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1395

### CODE REVIEW

**Comment by linawolf** [comment]
See also https://forge.typo3.org/issues/94420?next_issue_id=94418

**Review by lolli42 — CHANGES_REQUESTED** [review]
Huh?
Service API is not deprecated in v11.

**Comment by linawolf** [comment]
@lolli42 so if all of the Service Api depends on implementing the AbstractService and the AbstractService is deprecated, how can the Service API still exist?

**Comment by susannemoog** [comment]
> @lolli42 so if all of the Service Api depends on implementing the AbstractService and the AbstractService is deprecated, how can the Service API still exist?

I don't think the service api is dependent on the existence of AbstractService - from the rst and the code I'd rather say the part we have in the docs about the implementation is correctly describing which methods are needed, however, the first part of the docs stating the requirement to extend AbstractService is wrong - take a look here https://github.com/TYPO3/TYPO3.CMS/blob/5d3eff1b7aa0c8526ab4865011004b9d3c34a247/typo3/sysext/core/Classes/Utility/GeneralUtility.php#L3544 for details on that. 

Additionally, we should probably add the hint from the rst file, that people should avoid building new services if possible.

**Comment by linawolf** [comment]
Ill move it to another PR and start afresh

**Pull request closed without merging**
