### PR TITLE
[TASK] Use admonition attention instead of important

### PR DESCRIPTION
**Pull request by linawolf**
As ".. important::" is displayed in green we decided a while back to replace it with ".. attention::"

releases: main, 11.5

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
Can't it be changed just in the CSS of the theme?

**Comment by linawolf** [comment]
There was discussion back and forward and in the end we decided to drop it. It has something to do with the overlaying sphinx theme. And also the difference between important and attention is minimal. So we decided it was sufficient to remove it.

**Comment by brotkrueml** [comment]
> There was discussion back and forward and in the end we decided to drop it. It has something to do with the overlaying sphinx theme. And also the difference between important and attention is minimal. So we decided it was sufficient to remove it.

So please, add such information to the commit message or as comment.

**Review by brotkrueml — APPROVED** [review]

**Comment by linawolf** [comment]
"As ".. important::" is displayed in green we decided a while back to replace it with ".. attention::""

**Pull request merged**
