### PR TITLE
Add getContext method and description

### PR DESCRIPTION
**Pull request by remonator**
I suggest to add a description of the `getContext()` method. The text is inspired by the corresponding API description. While it exists in the API, it might be hard to find there without knowing the class.

### CODE REVIEW

**Review by linawolf — APPROVED** [review]

**Review by mbrodala — APPROVED** [review]

**Comment by sypets** [comment]
Should this be backported to 10.4 and 9.5 (as the function exists there as well)?

**Comment by linawolf** [comment]
@remonator do we need to backport this change to 10.4 and 9.5?

**Comment by remonator** [comment]
> 
> 
> @remonator do we need to backport this change to 10.4 and 9.5?

Yes please, since 10.4 is the current stable release (and probably a popular choice in the documentation's version selection) and the method exists in 9.5 as well.

**Comment by linawolf** [comment]
Backported to 10.4 and 9.5

**Pull request merged**
