### PR TITLE
[BUGFIX] Correct some rendering warnings in v11.5

### PR DESCRIPTION
**Pull request by brotkrueml**
Fixed warnings:

WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.typo3.org/c/typo3/cms-core/11.5/en-us/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://docs.typo3.org/c/typo3/cms-core/11.5/en-us/objects.inv

InputError: [Errno 2] No such file or directory: '/ALL/Makedir/SYMLINK_THE_PROJECT/Documentation/_includes/EventsContributeNote.rst.txt'.

./Documentation/ApiOverview/CommandControllers/Tutorial.rst:65: WARNING: Explicit markup ends without a blank line; unexpected unindent.

./Documentation/ApiOverview/Backend/BackendRouting.rst:21: ERROR: Error in "code-block" directive

./Documentation/ApiOverview/DirectoryStructure/LegacyInstallations.rst:16: WARNING: Explicit markup ends without a blank line; unexpected unindent.

./Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst:48: ERROR: Unknown directive type "extension-naming-extensionName".

./Documentation/ApiOverview/Internationalization/LocalizationApi/Index.rst: WARNING: document isn't included in any toctree

./Documentation/ApiOverview/FlexForms/Index.rst:63: WARNING: unknown document: ext_lowlevel:Index

./Documentation/ApiOverview/Fluid/Index.rst:26: WARNING: unknown document: t3extbasebook:Index

./Documentation/ApiOverview/Index.rst:11: WARNING: undefined label: sitemap

./Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst:155: WARNING: undefined label: t3tsconfig:global-page-tsconfig-v11-v12

./Documentation/ExtensionArchitecture/HowTo/BackendModule/BackendModuleApi/Index.rst:8: WARNING: undefined label: t3extbasebook:fluid-start
./Documentation/ExtensionArchitecture/HowTo/BackendModule/BackendModuleApi/Index.rst:8: WARNING: undefined label: t3extbasebook:controlling-the-flow-with-controllers
./Documentation/ExtensionArchitecture/HowTo/BackendModule/BackendModuleApi/Index.rst:25: WARNING: undefined label: ext-tables.php
./Documentation/ExtensionArchitecture/HowTo/BackendModule/BackendModulesWithExtbase/BackendModuleApiWithExtbase.rst:9: WARNING: undefined label: t3extbasebook:fluid-start
./Documentation/ExtensionArchitecture/HowTo/BackendModule/BackendModulesWithExtbase/BackendModuleApiWithExtbase.rst:9: WARNING: undefined label: t3extbasebook:controlling-the-flow-with-controllers

./Documentation/ExtensionArchitecture/HowTo/Localization/Index.rst:9: WARNING: unknown document: t3translate:Index

./Documentation/ExtensionArchitecture/HowTo/Localization/Index.rst:9: WARNING: unknown document: t3translate:Index

./Documentation/Security/GuidelinesExtensionDevelopment/Index.rst:31: WARNING: undefined label: t3tca:columns-email
./Documentation/Security/GuidelinesExtensionDevelopment/Index.rst:31: WARNING: undefined label: t3coreapi:extbase_validation

./Documentation/Testing/WritingFunctional.rst:211: WARNING: Pygments lexer name 'csv' is not known

./Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst:103: WARNING: Could not lex literal_block as "nginx". Highlighting skipped.

./Documentation/ApiOverview/PageTypes/RedirectHeaders.rst:23: WARNING: Could not lex literal_block as "http". Highlighting skipped.
./Documentation/ApiOverview/PageTypes/RedirectHeaders.rst:32: WARNING: Could not lex literal_block as "http". Highlighting skipped.

Releases: 11.5

### CODE REVIEW

**Comment by linawolf** [comment]
Moving the files from internationalization to localization, did you also prepare a redirect? Or is one already in place and was only forgotten?

**Comment by brotkrueml** [comment]
> Moving the files from internationalization to localization, did you also prepare a redirect? Or is one already in place and was only forgotten?

I assume, that was a backport which added this to 11.5. In v11.5 the "Localization" folder is in place, in v12 it is moved to Internationalization. The rendering warned about an orphan page (which was this). So I don't think we need a redirect here in v11 as that section was never linked.

**Comment by linawolf** [comment]
They where moved from Internationalization to localization in the past and are now available as Localization: https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Localization/Index.html

**Comment by linawolf** [comment]
The folder is also called "localization" in v.12 But I assume you are right about them needing to be moved from internationalization to localization in v11 as they are currently missing

**Review by linawolf — APPROVED** [review]

**Pull request merged**
