### PR TITLE
Feature: #95105 - New PSR-14 DatabaseRecordList events

### PR DESCRIPTION
**Pull request by linawolf**
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Feature-95105-NewPSR-14DatabaseRecordListEvents.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449

depends https://github.com/TYPO3-Documentation/t3docs-screenshots/pull/234

releases: master, 11.5

### CODE REVIEW

**Comment by susannemoog** [comment]
Why are these events using different formatting from all other events? If we want to change that, we should change that once for all of them - I fear introducing multiple formats will only lead to chaos :/

**Comment by linawolf** [comment]
From what I understood this is more then just a different formatting. It is actually a semantic syntax. 

I would is then even possible to link to classes and functions, for example

```
:php:func:`LibraryClass::instanceMethod`
```

**Comment by susannemoog** [comment]
Yes, I agree - I'd love to have the new syntax for everything, I just wanted to avoid introducing it partially.

**Comment by linawolf** [comment]
So I converted all the Events into Phpdomain syntax. The Api includes are automatically generated. Merging however now also depends on changes to the screenshot tool that must be merged first: https://github.com/TYPO3-Documentation/t3docs-screenshots/pull/234

**Comment by linawolf** [comment]
I added all the doc comments of the classes

**Review by susannemoog — APPROVED** [review]
This looks perfect <3 Thanks a lot!

**Pull request merged**
