### PR TITLE
[TASK] Embed API for various expression builder expressions

### PR DESCRIPTION
**Pull request by brotkrueml**
Releases: main, 12.4

### CODE REVIEW

**Comment by brotkrueml** [comment]
Waiting for https://github.com/TYPO3-Documentation/codesnippet/pull/27 to be merged.

**Comment by brotkrueml** [comment]
@linawolf I now have the warning:

Duplicate anchor "typo3-cms-core-database-query-expression-expressionbuilder" for link type "php:class" in document "ApiOverview/Database/ExpressionBuilder/Index". The anchor is already used at "ApiOverview/Database/ExpressionBuilder/Index" {"rst-file":"ApiOverview/Database/ExpressionBuilder/Index.rst"}

Maybe we can add something like `noindex` to `php:class`? In this example, the method is in the foreground, not the class. And mostly, also the method should not be linkable IMHO.

**Comment by linawolf** [comment]
Please open a ticket in the phpdomain tool to discuss this? as in sphinx the methods are linkable I kept that functionality and it might be breaking to drop it?

**Comment by brotkrueml** [comment]
Won't work on it in the next time.

**Comment by linawolf** [comment]
@brotkrueml the `:noindex:` property is available now for all php-domain items which can resolve the warning. Would you like to continue on this or would you like me to take over?

**Comment by brotkrueml** [comment]
Won't work on it in the next time.

**Comment by linawolf** [comment]
Can I take over?

**Comment by linawolf** [comment]
Merging into a feature branch so I can keep working on it

**Pull request merged**
