### PR TITLE
[FEATURE] #101553 - Auto-create DB fields from TCA columns for various types

### PR DESCRIPTION
**Pull request by brotkrueml**
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/697
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/696
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/688
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/687
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/677
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/666
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/660
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/655
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/652
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/648
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/647
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/641
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/632
Releases: main

### CODE REVIEW

**Comment by linawolf** [comment]
Do we also have to mention this in each type? I think we had a text-snippet for that in the other types?

**Comment by brotkrueml** [comment]
This is the overview on the "ext_tables.sql" page (and when it was introduced). In The TCA reference it is also mentioned for the according types already (which also links to this page).

**Comment by linawolf** [comment]
With the "resolves" you will close all these tickets. Is that really intended?

**Comment by brotkrueml** [comment]
> With the "resolves" you will close all these tickets. Is that really intended?

Yup, every issue has just one type covered. I already added the notes in TCA docs for those types separately. Now, they are also mentioned in this part of the docs. This closes every single issue.

**Comment by brotkrueml** [comment]
@linawolf Is this PR okay like done and you can approve it?

**Review by linawolf — APPROVED** [review]

**Pull request merged**
