### PR TITLE
[BUGFIX] Fix spelling errors, standardize brand names, fix event listener examples

### PR DESCRIPTION
**Pull request by sandoba**
- fix spelling errors
- standardize spelling of "YouTube", "PHP", "Composer", "YAML" outside of commands
- add missing "declare(strict_types=1);" for a few event listener examples
- move "AsEventListener" attribute before class declaration for a few event listener examples

### CODE REVIEW

**Review by garvinhicking — APPROVED** [review]
Great, thanks a lot! All these changes are a nice unification and fix mistakes 😊

**Comment by garvinhicking** [comment]
I wonder if we could backport a few of these fixes to the 12.4 tree (not the event attribute ones because only applicable to v13 IIRC).

Would you be willing to create a PR for this against the 12.4 branch? A cherry-pick with some resolved conflicts might work.

**Comment by sandoba** [comment]
I don't have the resources atm but I would guess most changes of commit _3e7a2c3_ would be valid in 12.4 as well while those in _c7d5b34_ only apply to the current version for 13.x.

**Comment by garvinhicking** [comment]
Ack! Will try! Thanks for the feedback :)

**Pull request merged**
