### PR TITLE
#94312 - Removed BE/loginSecurityLevel and FE/loginSecurityLevel options

### PR DESCRIPTION
**Pull request by franzholz**
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.3/Important-94312-RemovedBEloginSecurityLevelAndFEloginSecurityLevelOptions.html

### CODE REVIEW

**Comment by linawolf** [comment]
Thanks for catching this!

Have you checked if they are still mentioned in main? If so we should make this change on main and then backport into 11.5 so that we can use the  new automatic backport workflow.

**Review by linawolf — CHANGES_REQUESTED** [review]
Thanks for catching this!

Have you checked if they are still mentioned in main? If so we should make this change on main and then backport into 11.5 so that we can use the new automatic backport workflow.

**Comment by franzholz** [comment]
The same thing must also be fixed in the main branch.
The removed global variables are still mentioned there:

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Authentication/Index.html


$GLOBALS['TYPO3_CONF_VARS']['BE']['loginSecurityLevel'] or $GLOBALS['TYPO3_CONF_VARS']['FE']['loginSecurityLevel']

**Comment by linawolf** [comment]
Please make a PR for main then, we will backport it to 11.5

**Comment by franzholz** [comment]
A new PR is out.

**Comment by linawolf** [comment]
Closing this PR as the other one gets backported

**Pull request closed without merging**
