### PR TITLE
[TASK] add cacheCmd system and temp_cached

### PR DESCRIPTION
**Pull request by kaystrobach**

### CODE REVIEW

**Comment by kaystrobach** [comment]
looks good - thank you for taking care

**Comment by marble** [comment]
:-))

**Comment by liayn** [comment]
IMO we have to explain what "temp_cached" is

**Comment by kaystrobach** [comment]
`temp_cached` is just an alias for `system` in this case, so i added both

**Comment by marble** [comment]
Yes, please explain and be explicite.

**Pull request merged**
