### PR TITLE
[SECURITY] Update information about Indexes

### PR DESCRIPTION
**Pull request by sypets**
Previously, a `<Directory>` directive was used in the code snippet
and a caption was added later that this applies for .htaccess
file. But Directory directives in .htaccess are not supported by Apache. Directory can
be used in Context "server config" or "virtual host", but not
.htaccess.

The following has been changed:

1. Do not use` <Directory>` directive in the code snippet for .htaccess

2. Differentiate between .htaccess and server config

3. Links to Apache configuration are added.

4. Directives already in TYPO3 core .htaccess mentioned

5. Add configuration for Nginx and ISS as well

Resolves: #1990
Related: #1993

### CODE REVIEW

**Review by linawolf — CHANGES_REQUESTED** [review]
Do not merge without a review from Oliver Hader.

**Review by ohader — CHANGES_REQUESTED** [review]
* distinguish in the docs between
  + server configuration e.g `/etc/apache2/sites-available/myhost.conf`, and
  + project configuration, e.g. `/var/www/myhost/public/.htaccess`
* explain which example refers to which location
* emphasize what is the actual suggestion & use the core's declaration
```
<IfModule mod_autoindex.c>
        Options -Indexes
</IfModule>
```
* (optional) include the same for at least nginx and IIS, e.g. get some inspiration from https://www.invicti.com/blog/web-security/disable-directory-listing-web-servers/

**Comment by sypets** [comment]
Pushed my final version. 

@ohader  and @tomwarwick would like to review, @tomwarwick would possibly like to make further language improvements.

Explanation is in the [commits](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1991/commits).

**Review by tomwarwick — APPROVED** [review]

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
@ohader can it be merged like this? If so please approve

**Comment by linawolf** [comment]
Merging now. please make another PR if changes are still required

**Pull request merged**
