### PR TITLE
Update "Using container->get()" on page DependencyInjection

### PR DESCRIPTION
**Pull request by DavidBruchmann**
remove '[WIP]', fix typo.
related to #2339

TODO: Rewrite content

### CODE REVIEW

**Review by brotkrueml — CHANGES_REQUESTED** [review]
We should emphasize more that injecting the DI container and using $container->get( is considered an anti-pattern and there are only rare use cases where this might be used.

When something like this is needed service locators might be a better way:
https://symfony.com/doc/current/service_container/service_subscribers_locators.html

**Comment by DavidBruchmann** [comment]
That has to be done at another time if you considered that part for me.  
Like @sypets pointed out we should primarily getting rid of '[WIP]', I leave open if we could use some kind of TODO inside the documentation.

**Comment by brotkrueml** [comment]
> That has to be done at another time if you considered that part for me. Like @sypets pointed out we should primarily getting rid of '[WIP]' (also independent of any links), I leave open if we could use some kind of TODO inside the documentation.

Just removing the WIP is not helpful, as it looks then, using the container inside classes is the way to go, the WIP gives at least a hint, you should rethink what it is described there. 

I suggest: Either we leave the WIP as is for the time being or put an "attention" in this section, saying this is not the recommended way. Another possibility would be to just remove the whole section. If you are dealing with factories or registries you know what you are doing and you are hopefully familiar with DI. TYPO3 uses Symfony DI, so the Symfony DI docs are the primary information source. We do not have to rewrite everything from them. An Introduction and the TYPO3-specific details should be enough for this chapter. And then links to the Symfony docs.

So I opt now for removing this section.

**Comment by DavidBruchmann** [comment]
I think `$container->get()` is a built in functionality and should be mentioned.  
I agree that the kind of presentation might be bad, perhaps we even leave the headline away or change it.  
About Mentioning the Symfony solution I'm open, TYPO3 is relying much on Symfony already anyway--else I'd see it more critical as external niche solution.  
The explanation about the choice of solution is obviously most important.

**Comment by DavidBruchmann** [comment]
Concerning `WIP` @sypets proposed a clear way how to mark things that need rework and I think it's a good proposition having a standardized and for readers understandable marking. `WIP` at the beginning of a line belongs certainly not to it.

**Comment by linawolf** [comment]
@DavidBruchmann yes  we can use `.. todo: ` as a comment, I agree that we should remove all WIPs from the visible documentation. However if there is some information missing and we need to give a hint to ppl we can additionally add a note box or some such.

**Comment by brotkrueml** [comment]
When the others are okay with that, then do it. But I won't approve it. Not all functionality should be used by the unexperienced. An the experienced know when to use it and when not (and can read the Symfony documentation).

**Comment by linawolf** [comment]
@DavidBruchmann could you ad a todo then? @brotkrueml would you be willing to remove your review then, as it blocks merging?

**Comment by linawolf** [comment]
Closed for lack of reaction

**Pull request closed without merging**
